// ─── Skill Tree Data ───────────────────────────────────────────────────────
// Aligned with ACM/IEEE CC2020 (Sec. 5.2): Competency = Knowledge + Skills + Dispositions.
// Shallow 3-layer structure: Foundation → Competency clusters → Career targets.
// skillLevel: Bloom-style (Remember, Understand, Apply, Analyze, Evaluate, Create).
// dispositions (softSkills): CC2020 disposition/characteristics.
// competencies: short knowledge/skill bullets for reporting.

const SKILLS = [

  // ══════════════════════════════════════════════════
  //  CORE HUB
  // ══════════════════════════════════════════════════
  {
    id: "root",
    label: "Lifelong Learning\n& Adaptability",
    icon: "♾️",
    tier: "root",
    branch: "common",
    x: 700, y: 720,
    radius: 52,
    desc: "The drive to continuously update your skills, embrace new tools, and adapt in a rapidly evolving field. In AI and cybersecurity, yesterday's best practice can become tomorrow's vulnerability — adaptability is not optional, it is the foundation of everything.",
    skillLevel: "Understand",
    competencies: ["Understand core computing and professional context", "Self-directed learning and reflection"],
    dispositions: ["Adaptable", "Self-directed", "Responsible"],
    tools: [],
    learningSources: { courses: [], labs: [], projects: [] },
    prereqs: [],
    careers: [],
    salary: null,
    xp: 0,
  },

  // ══════════════════════════════════════════════════
  //  4 COMPETENCY CLUSTERS
  // ══════════════════════════════════════════════════
  {
    id: "foundations_cluster",
    label: "Foundations",
    icon: "🏗️",
    tier: "advanced",
    branch: "common",
    x: 160, y: 450,
    radius: 42,
    desc: "Core transferable skills every professional needs regardless of specialization — thinking clearly, solving problems methodically, managing time under pressure, and reflecting honestly on your own practice.",
    skillLevel: "Apply",
    competencies: ["Knowledge of problem-solving methods and core computing concepts", "Apply analytical and critical thinking", "Problem solving and troubleshooting", "Time management and task organization"],
    dispositions: ["Problem Solving", "Critical Thinking", "Self-Learning", "Time Management", "Reflective Practice"],
    softSkills: ["Problem Solving", "Critical Thinking", "Self-Learning", "Time Management", "Reflective Practice"],
    tools: [],
    learningSources: { courses: [], labs: [], projects: [] },
    prereqs: ["root"],
    careers: ["Data Scientist", "Security Analyst", "Penetration Tester", "Threat Intel Engineer"],
    salary: null,
    xp: 80,
  },
  {
    id: "comm_teamwork",
    label: "Communication\n& Teamwork",
    icon: "🤝",
    tier: "advanced",
    branch: "ai",
    x: 490, y: 430,
    radius: 42,
    desc: "Translating complex technical work across disciplines, listening actively, and collaborating effectively in cross-functional teams. No AI system or security posture is built alone — communication determines whether good work has real impact.",
    skillLevel: "Apply",
    competencies: ["Oral and written technical communication", "Collaboration and teamwork", "Active listening and conflict resolution"],
    dispositions: ["Technical Communication", "Collaboration", "Active Listening", "Conflict Resolution"],
    softSkills: ["Technical Communication", "Collaboration", "Active Listening", "Conflict Resolution"],
    tools: [],
    learningSources: { courses: [], labs: [], projects: [] },
    prereqs: ["root"],
    careers: ["AI Research Scientist", "Data Scientist", "ML Engineer"],
    salary: null,
    xp: 80,
  },
  {
    id: "ethics_resp",
    label: "Ethics &\nResponsibility",
    icon: "⚖️",
    tier: "advanced",
    branch: "cyber",
    x: 910, y: 430,
    radius: 42,
    desc: "Applying moral judgment when designing AI systems or conducting security work — responsible disclosure, data privacy, algorithmic fairness, and understanding the broader societal impact of the systems you build and defend.",
    skillLevel: "Evaluate",
    competencies: ["Evaluate ethical and professional choices", "Understand security, privacy, and societal impact"],
    dispositions: ["Ethical Decision Making", "Professional Ethics", "AI & Cybersecurity Ethics", "Social Impact Awareness"],
    softSkills: ["Ethical Decision Making", "Professional Ethics", "AI & Cybersecurity Ethics", "Social Impact Awareness"],
    tools: [],
    learningSources: { courses: [], labs: [], projects: [] },
    prereqs: ["root"],
    careers: ["AI Security Engineer", "Adversarial ML Engineer", "IoT Security Engineer", "Security Architect"],
    salary: null,
    xp: 80,
  },
  {
    id: "leadership_innov",
    label: "Leadership &\nInnovation",
    icon: "🚀",
    tier: "advanced",
    branch: "hybrid",
    x: 1230, y: 450,
    radius: 42,
    desc: "Driving projects forward, inspiring teams, thinking creatively, and planning strategically. Leaders in AI and cybersecurity don't just solve today's problems — they anticipate tomorrow's challenges and bring others along for the journey.",
    skillLevel: "Create",
    competencies: ["Knowledge of project lifecycle and team dynamics", "Project and task organization", "Creative thinking and strategic planning", "Leadership and coordination"],
    dispositions: ["Project Management", "Creative Thinking", "Leadership Skills", "Strategic Planning"],
    softSkills: ["Project Management", "Creative Thinking", "Leadership Skills", "Strategic Planning"],
    tools: [],
    learningSources: { courses: [], labs: [], projects: [] },
    prereqs: ["root"],
    careers: ["Security Architect", "Incident Response Engineer", "Resilient Autonomous Systems Engineer", "ML Engineer"],
    salary: null,
    xp: 80,
  },

  // ══════════════════════════════════════════════════
  //  CAREER ENDPOINTS — AI
  // ══════════════════════════════════════════════════
  {
    id: "data_sci",
    label: "Data\nScientist",
    icon: "📊",
    tier: "career",
    branch: "ai",
    x: 200, y: 100,
    radius: 44,
    desc: "Extracts insights from complex datasets to drive business decisions. Works at the intersection of statistics, domain expertise, and software engineering.",
    tools: ["Python", "R", "Tableau", "SQL", "Jupyter", "Spark"],
    softSkills: ["Communication", "Analytical Thinking", "Business Translation", "Curiosity"],
    learningSources: {
      courses: ["Applied Data Science with Python (Coursera)", "Kaggle Data Science micro-courses"],
      labs: ["Kaggle notebook competitions", "Seaborn & Matplotlib visualisation exercises"],
      projects: ["End-to-end EDA and prediction project", "Build an interactive data dashboard"],
    },
    prereqs: ["foundations_cluster", "comm_teamwork"],
    careers: [],
    salary: "$105K – $165K / yr",
    xp: 200,
  },
  {
    id: "ml_eng",
    label: "ML\nEngineer",
    icon: "🤖",
    tier: "career",
    branch: "ai",
    x: 390, y: 80,
    radius: 44,
    desc: "Designs, trains, and deploys production-grade ML systems. A blend of software engineering discipline and data science expertise.",
    tools: ["PyTorch", "TensorFlow", "Kubernetes", "FastAPI", "MLflow"],
    softSkills: ["Analytical Thinking", "Problem Solving", "Collaboration", "Communication"],
    learningSources: {
      courses: ["MLOps Specialization (DeepLearning.AI)", "Full Stack Deep Learning"],
      labs: ["Build and serve a model with FastAPI", "Kubeflow pipeline lab"],
      projects: ["Deploy a production ML system with monitoring", "A/B test a model in a staging environment"],
    },
    prereqs: ["foundations_cluster", "leadership_innov"],
    careers: [],
    salary: "$130K – $200K / yr",
    xp: 200,
  },
  {
    id: "ai_researcher",
    label: "AI Research\nScientist",
    icon: "🧬",
    tier: "career",
    branch: "ai",
    x: 70, y: 80,
    radius: 44,
    desc: "Invents new AI algorithms and architectures. Publishes research, works on frontier models, and often requires a PhD or equivalent research experience.",
    tools: ["PyTorch", "JAX", "Hugging Face", "LaTeX", "CUDA"],
    softSkills: ["Curiosity & Continuous Learning", "Creativity / Innovation", "Analytical Thinking", "Scientific Communication"],
    learningSources: {
      courses: ["Deep Learning Specialization (DeepLearning.AI)", "CS231n / CS224n (Stanford)"],
      labs: ["Reproduce a landmark research paper (ResNet, BERT)", "Hugging Face research model lab"],
      projects: ["Publish an AI research blog post or preprint", "Novel architecture experiment on a benchmark"],
    },
    prereqs: ["comm_teamwork", "leadership_innov"],
    careers: [],
    salary: "$160K – $350K+ / yr",
    xp: 200,
  },

  // ══════════════════════════════════════════════════
  //  CAREER ENDPOINTS — CYBERSECURITY
  // ══════════════════════════════════════════════════
  {
    id: "pen_tester",
    label: "Penetration\nTester",
    icon: "🎯",
    tier: "career",
    branch: "cyber",
    x: 920, y: 130,
    radius: 44,
    desc: "Ethically hacks systems to find and report vulnerabilities before malicious actors can exploit them. Operates under legal agreements and structured methodologies.",
    tools: ["Metasploit", "Burp Suite", "Kali Linux", "OWASP", "Cobalt Strike"],
    softSkills: ["Creativity", "Problem Solving", "Curiosity", "Ethical Judgment"],
    learningSources: {
      courses: ["OSCP (Offensive Security)", "TCM Security: Practical Bug Bounty"],
      labs: ["HackTheBox Pro Labs", "TryHackMe offensive paths"],
      projects: ["Submit a bug bounty finding", "Write a full penetration test report on a lab VM"],
    },
    prereqs: ["foundations_cluster", "ethics_resp"],
    careers: [],
    salary: "$95K – $155K / yr",
    xp: 200,
  },
  {
    id: "sec_arch",
    label: "Security\nArchitect",
    icon: "🏛",
    tier: "career",
    branch: "cyber",
    x: 1100, y: 100,
    radius: 44,
    desc: "Designs and oversees the security posture of entire organizations. Requires broad expertise across networking, cloud, identity, and risk management.",
    tools: ["NIST Framework", "AWS/GCP/Azure Security", "Zero Trust", "SIEM"],
    softSkills: ["Strategic Thinking", "Communication", "Risk Assessment", "Leadership"],
    learningSources: {
      courses: ["CISSP Exam Prep", "AWS/GCP Security Specialty certification"],
      labs: ["Design a zero-trust architecture on paper", "Cloud security misconfiguration lab"],
      projects: ["Enterprise security assessment report", "Threat model a real application using STRIDE"],
    },
    prereqs: ["leadership_innov", "ethics_resp"],
    careers: [],
    salary: "$140K – $220K / yr",
    xp: 200,
  },
  {
    id: "ir_analyst",
    label: "Incident Response\nEngineer",
    icon: "🚨",
    tier: "career",
    branch: "cyber",
    x: 1270, y: 130,
    radius: 44,
    desc: "Investigates active breaches, contains damage, eradicates threats, and leads recovery. Acts as the digital first responder when an organization is under attack.",
    tools: ["Splunk", "CrowdStrike", "Volatility", "The Hive", "Elastic"],
    softSkills: ["Crisis Decision Making", "Attention to Detail", "Communication", "Team Coordination"],
    learningSources: {
      courses: ["GCIH (GIAC Certified Incident Handler)", "SANS FOR508: Digital Forensics"],
      labs: ["Blue Team Labs Online: IR scenarios", "LetsDefend incident response labs"],
      projects: ["Incident response simulation exercise", "Build a detection-to-response playbook"],
    },
    prereqs: ["leadership_innov", "ethics_resp"],
    careers: [],
    salary: "$90K – $150K / yr",
    xp: 200,
  },

  // ══════════════════════════════════════════════════
  //  HYBRID CAREERS
  // ══════════════════════════════════════════════════
  {
    id: "ai_sec_eng",
    label: "AI Security\nEngineer",
    icon: "🔐",
    tier: "career",
    branch: "hybrid",
    x: 620, y: 120,
    radius: 44,
    desc: "Secures AI/ML systems against adversarial attacks — data poisoning, model inversion, prompt injection, and model theft. A rare, high-demand intersection role.",
    tools: ["CleverHans", "ART (IBM)", "MLflow", "OWASP ML", "TensorFlow Privacy"],
    softSkills: ["Adversarial Thinking", "Analytical Thinking", "Collaboration", "Ethical Judgment"],
    learningSources: {
      courses: ["AI Security (MITRE ATLAS free training)", "Adversarial Robustness Toolbox tutorials"],
      labs: ["Adversarial ML Exercise (IBM ART)", "OWASP ML Security Top 10 lab"],
      projects: ["Secure Model Deployment pipeline", "Demonstrate a data poisoning attack and its defence"],
    },
    prereqs: ["ethics_resp", "leadership_innov"],
    careers: [],
    salary: "$150K – $230K / yr",
    xp: 250,
  },
  {
    id: "threat_intel",
    label: "Threat Intel\nEngineer",
    icon: "🔍",
    tier: "career",
    branch: "hybrid",
    x: 780, y: 120,
    radius: 44,
    desc: "Uses AI and ML to detect, classify, and predict emerging cyber threats at scale. Combines statistical anomaly detection with deep threat intelligence tradecraft.",
    tools: ["MITRE ATT&CK", "OpenCTI", "ML anomaly models", "STIX/TAXII"],
    softSkills: ["Pattern Recognition", "Analytical Thinking", "Communication", "Curiosity"],
    learningSources: {
      courses: ["MITRE ATT&CK Fundamentals (free)", "SANS FOR578: Cyber Threat Intelligence"],
      labs: ["OpenCTI platform setup lab", "STIX/TAXII data modelling exercise"],
      projects: ["Threat intelligence report on a real APT group", "Build an AI anomaly detector for network logs"],
    },
    prereqs: ["foundations_cluster", "ethics_resp"],
    careers: [],
    salary: "$110K – $180K / yr",
    xp: 250,
  },

  // ══════════════════════════════════════════════════
  //  CAREER ENDPOINTS — AI SYSTEMS (panel-only)
  // ══════════════════════════════════════════════════
  {
    id: "applied_ai_eng",
    label: "Applied AI\nEngineer",
    icon: "⚡",
    tier: "career",
    branch: "ai",
    panelOnly: true,
    x: 0, y: 0, radius: 44,
    desc: "Translates AI research into real-world products — recommendation systems, search engines, NLP pipelines, and vision systems. Heavy emphasis on production reliability and scale.",
    tools: ["PyTorch", "TensorFlow", "FastAPI", "Docker", "Redis", "gRPC"],
    softSkills: ["Problem Solving", "Collaboration", "Strategic Thinking", "Adaptability"],
    learningSources: {
      courses: ["Full Stack Deep Learning", "Designing ML Systems (book by Chip Huyen)"],
      labs: ["Build an ML-powered REST API", "System design mock interviews for ML"],
      projects: ["Deploy a recommendation system to production", "Build a real-time ML feature pipeline"],
    },
    prereqs: ["foundations_cluster", "leadership_innov"],
    careers: [],
    salary: "$125K – $195K / yr",
    xp: 200,
  },

  // ══════════════════════════════════════════════════
  //  CAREER ENDPOINTS — CYBERSECURITY (panel-only)
  // ══════════════════════════════════════════════════
  {
    id: "sec_analyst",
    label: "Security\nAnalyst",
    icon: "🔎",
    tier: "career",
    branch: "cyber",
    panelOnly: true,
    x: 0, y: 0, radius: 44,
    desc: "Monitors networks and systems for threats, triages security alerts, and performs initial investigation of potential incidents. Often the entry point into a SOC career.",
    tools: ["Splunk", "QRadar", "Elastic SIEM", "Wireshark", "MITRE ATT&CK"],
    softSkills: ["Attention to Detail", "Analytical Thinking", "Communication", "Persistence"],
    learningSources: {
      courses: ["CompTIA CySA+", "Google Cybersecurity Certificate (Coursera)"],
      labs: ["Splunk Boss of the SOC (BOTS v1)", "LetsDefend SOC analyst labs"],
      projects: ["SOC alert triage simulation write-up", "Build a SIEM dashboard for a home lab"],
    },
    prereqs: ["foundations_cluster", "ethics_resp"],
    careers: [],
    salary: "$70K – $120K / yr",
    xp: 150,
  },

  // ══════════════════════════════════════════════════
  //  CAREER ENDPOINTS — EDGE / EMBEDDED AI (panel-only)
  // ══════════════════════════════════════════════════
  {
    id: "edge_ai_eng",
    label: "Edge AI\nEngineer",
    icon: "📡",
    tier: "career",
    branch: "edge",
    panelOnly: true,
    x: 0, y: 0, radius: 44,
    desc: "Deploys and optimizes AI models on resource-constrained hardware — smartphones, cameras, sensors, and microcontrollers. Specializes in model compression, quantization, and on-device inference.",
    tools: ["TensorFlow Lite", "ONNX", "OpenVINO", "NVIDIA Jetson", "CoreML", "TVM"],
    softSkills: ["Systems Thinking", "Problem Solving", "Collaboration", "Adaptability"],
    learningSources: {
      courses: ["Edge AI Systems (Coursera)", "TinyML Specialization (HarvardX/edX)"],
      labs: ["Deploy a model on Raspberry Pi / Jetson Nano", "TensorFlow Lite quantisation lab"],
      projects: ["Real-time object detection on a mobile device", "Benchmark three compression strategies on a CNN"],
    },
    prereqs: ["foundations_cluster", "leadership_innov"],
    careers: [],
    salary: "$110K – $175K / yr",
    xp: 200,
  },
  {
    id: "embedded_ml_eng",
    label: "Embedded ML\nEngineer",
    icon: "🔧",
    tier: "career",
    branch: "edge",
    panelOnly: true,
    x: 0, y: 0, radius: 44,
    desc: "Writes ML inference code for bare-metal microcontrollers and FPGAs. Bridges hardware engineering and machine learning — optimizing every byte and clock cycle.",
    tools: ["TensorFlow Micro", "C/C++", "CMSIS-NN", "Arduino", "STM32", "FPGA"],
    softSkills: ["Attention to Detail", "Analytical Thinking", "Problem Solving", "Persistence"],
    learningSources: {
      courses: ["Embedded Systems (Coursera/EE)", "TensorFlow Micro (Arduino/ST)"],
      labs: ["Keyword spotting demo on Arduino Nano 33 BLE", "CMSIS-NN inference lab"],
      projects: ["Keyword spotting model on a microcontroller", "FPGA-accelerated ML inference demo"],
    },
    prereqs: ["foundations_cluster", "ethics_resp"],
    careers: [],
    salary: "$105K – $165K / yr",
    xp: 200,
  },
  {
    id: "robotics_eng",
    label: "Robotics & Autonomous\nSystems Engineer",
    icon: "🦾",
    tier: "career",
    branch: "edge",
    panelOnly: true,
    x: 0, y: 0, radius: 44,
    desc: "Builds intelligent autonomous agents — drones, self-driving vehicles, robotic arms, and UAVs. Combines computer vision, motion planning, and real-time control with ML.",
    tools: ["ROS/ROS2", "OpenCV", "PyTorch", "Gazebo", "SLAM algorithms", "C++"],
    softSkills: ["Systems Thinking", "Problem Solving", "Collaboration", "Adaptability"],
    learningSources: {
      courses: ["Robotics Specialization (Coursera/Penn)", "Self-Driving Car Engineer (Udacity)"],
      labs: ["ROS2 simulation lab (Gazebo)", "OpenCV vision pipeline lab"],
      projects: ["Autonomous navigation demo in simulation", "Computer vision object-tracking robot"],
    },
    prereqs: ["foundations_cluster", "leadership_innov"],
    careers: [],
    salary: "$115K – $185K / yr",
    xp: 200,
  },
  {
    id: "iot_sec_eng",
    label: "IoT Security\nEngineer",
    icon: "🌐",
    tier: "career",
    branch: "edge",
    panelOnly: true,
    x: 0, y: 0, radius: 44,
    desc: "Secures the vast landscape of connected devices — identifying firmware vulnerabilities, hardening device boot chains, and designing secure OTA update mechanisms.",
    tools: ["Firmware analysis", "Binwalk", "OpenWRT", "MQTT security", "Shodan", "Zigbee"],
    softSkills: ["Attention to Detail", "Analytical Thinking", "Problem Solving", "Ethical Judgment"],
    learningSources: {
      courses: ["IoT Security Fundamentals (SANS)", "Embedded Security (Coursera)"],
      labs: ["Firmware analysis with Binwalk", "MQTT security testing lab"],
      projects: ["IoT device security audit report", "Harden an off-the-shelf IoT device"],
    },
    prereqs: ["ethics_resp", "foundations_cluster"],
    careers: [],
    salary: "$100K – $160K / yr",
    xp: 200,
  },

  // ══════════════════════════════════════════════════
  //  CAREER ENDPOINTS — AI + CYBER HYBRID (panel-only)
  // ══════════════════════════════════════════════════
  {
    id: "adv_ml_eng",
    label: "Adversarial ML\nEngineer",
    icon: "⚔",
    tier: "career",
    branch: "hybrid",
    panelOnly: true,
    x: 0, y: 0, radius: 44,
    desc: "Researches and defends against adversarial attacks on AI — crafting and defeating adversarial examples, data poisoning campaigns, and model extraction attacks. One of the most cutting-edge roles in the field.",
    tools: ["CleverHans", "Foolbox", "IBM ART", "PyTorch", "MITRE ATLAS"],
    softSkills: ["Adversarial Thinking", "Curiosity", "Analytical Thinking", "Ethical Judgment"],
    learningSources: {
      courses: ["Adversarial ML (MITRE ATLAS training)", "Robust ML course (CMU)"],
      labs: ["Adversarial ML Exercise (Foolbox / CleverHans)", "MITRE ATLAS attack simulation"],
      projects: ["Attack and defend an ML model challenge", "Reproduce an adversarial example paper"],
    },
    prereqs: ["foundations_cluster", "ethics_resp"],
    careers: [],
    salary: "$140K – $220K / yr",
    xp: 250,
  },
  {
    id: "resilient_auto_eng",
    label: "Resilient Autonomous\nSystems Engineer",
    icon: "🛡",
    tier: "career",
    branch: "hybrid",
    panelOnly: true,
    x: 0, y: 0, radius: 44,
    desc: "Designs autonomous systems — drones, vehicles, robots — that remain safe and functional under cyberattack, sensor spoofing, and adversarial conditions. Combines robotics, AI safety, and cybersecurity.",
    tools: ["ROS2", "Formal verification", "MITRE ATT&CK for ICS", "Gazebo", "OpenCV"],
    softSkills: ["Systems Thinking", "Crisis Decision Making", "Strategic Thinking", "Problem Solving"],
    learningSources: {
      courses: ["Resilient Systems Design (MIT OpenCourseWare)", "Autonomous Vehicle Security (SANS)"],
      labs: ["ROS2 adversarial sensor spoofing simulation", "Fault injection lab on a robotic arm"],
      projects: ["Fault-tolerant autonomous navigation demo", "Red team a simulated autonomous vehicle pipeline"],
    },
    prereqs: ["leadership_innov", "ethics_resp"],
    careers: [],
    salary: "$130K – $210K / yr",
    xp: 250,
  },
];

// Build a lookup map for convenience
const SKILL_MAP = Object.fromEntries(SKILLS.map(s => [s.id, s]));

// Edge definitions: [from_id, to_id]
// Auto-generated from prereqs but we define them explicitly for control
const EDGES = SKILLS.flatMap(skill =>
  skill.prereqs.map(prereqId => ({ from: prereqId, to: skill.id }))
);
