// ─── Skill Tree Data ───────────────────────────────────────────────────────
// Layout: x,y in a 1400×900 SVG canvas (origin top-left)
// Tiers: root | foundation | branch | advanced | career
// Branch: common | ai | cyber | hybrid
// All non-career nodes represent soft skills

const SKILLS = [

  // ══════════════════════════════════════════════════
  //  ROOT
  // ══════════════════════════════════════════════════
  {
    id: "root",
    label: "Growth\nMindset",
    icon: "🌱",
    tier: "root",
    branch: "common",
    x: 700, y: 820,
    radius: 46,
    desc: "The universal foundation. Before mastering any domain, cultivating a growth mindset — the belief that abilities can be developed through dedication — sets the stage for continuous learning and resilience in fast-moving fields like AI and cybersecurity.",
    tools: [],
    learningSources: {
      courses: ["Mindset (book by Carol Dweck)", "Learning How to Learn (Coursera)"],
      labs: [],
      projects: ["Start a weekly learning journal", "Set and track 3-month skill goals"],
    },
    prereqs: [],
    careers: [],
    salary: null,
    xp: 0,
  },

  // ══════════════════════════════════════════════════
  //  FOUNDATION SOFT SKILLS
  // ══════════════════════════════════════════════════
  {
    id: "curiosity",
    label: "Curiosity &\nLearning",
    icon: "🔭",
    tier: "foundation",
    branch: "ai",
    x: 300, y: 660,
    radius: 36,
    desc: "Intellectual curiosity drives you to explore beyond requirements — reading papers, reverse-engineering systems, and asking 'what if?'. The most breakthrough discoveries in AI research and security come from relentlessly curious minds who pursue understanding for its own sake.",
    tools: [],
    learningSources: {
      courses: ["A Mind for Numbers (book, Barbara Oakley)", "Feynman Technique (YouTube masterclass)"],
      labs: ["Read one AI or security paper per week and summarise it"],
      projects: ["Write a blog post on something you discovered entirely on your own"],
    },
    prereqs: ["root"],
    careers: ["AI Research Scientist", "Penetration Tester", "Threat Intel Engineer"],
    salary: null,
    xp: 50,
  },
  {
    id: "analytical",
    label: "Analytical\nThinking",
    icon: "🧩",
    tier: "foundation",
    branch: "common",
    x: 540, y: 660,
    radius: 36,
    desc: "Breaking complex problems into smaller components, identifying patterns, and reasoning from evidence. This is the backbone of data science, threat analysis, and every form of engineering decision-making across both AI and cybersecurity.",
    tools: [],
    learningSources: {
      courses: ["Critical Thinking & Problem Solving (Coursera)", "Think Like a Programmer (book)"],
      labs: ["Logic puzzle practice (Brilliant.org)", "Root cause analysis exercises"],
      projects: ["Analyse a real-world system failure and document root causes with evidence"],
    },
    prereqs: ["root"],
    careers: ["Data Scientist", "Threat Intel Engineer", "Security Analyst"],
    salary: null,
    xp: 50,
  },
  {
    id: "communication",
    label: "Clear\nCommunication",
    icon: "💬",
    tier: "foundation",
    branch: "common",
    x: 860, y: 660,
    radius: 36,
    desc: "Translating technical findings into language that colleagues, clients, and decision-makers can act on. Whether writing an incident report or presenting model results to stakeholders, clarity and precision drive real-world impact.",
    tools: [],
    learningSources: {
      courses: ["Technical Writing (Google/Coursera)", "Presentation Zen (book, Garr Reynolds)"],
      labs: ["Write a 1-page technical explainer for a non-technical audience"],
      projects: ["Present a technical project to a mixed audience and gather structured feedback"],
    },
    prereqs: ["root"],
    careers: ["Data Scientist", "Security Architect", "AI Research Scientist"],
    salary: null,
    xp: 50,
  },
  {
    id: "attention",
    label: "Attention\nto Detail",
    icon: "🔍",
    tier: "foundation",
    branch: "cyber",
    x: 1100, y: 660,
    radius: 36,
    desc: "Precision matters enormously in security — a single misconfigured permission or overlooked log line can expose an entire system. In AI, data quality issues hide in the details. This skill keeps you methodical and thorough under pressure.",
    tools: [],
    learningSources: {
      courses: ["Detail Orientation in Tech Roles (LinkedIn Learning)"],
      labs: ["Log review exercises", "Spot-the-bug code review challenges"],
      projects: ["Conduct a full code or config review and document every issue found with severity ratings"],
    },
    prereqs: ["root"],
    careers: ["Security Analyst", "Incident Response Engineer", "Embedded ML Engineer"],
    salary: null,
    xp: 50,
  },

  // ══════════════════════════════════════════════════
  //  SKILL-BUILDING LAYER
  // ══════════════════════════════════════════════════
  {
    id: "creative_thinking",
    label: "Creative\nThinking",
    icon: "🎨",
    tier: "branch",
    branch: "ai",
    x: 200, y: 490,
    radius: 32,
    desc: "The ability to imagine novel solutions, connect unrelated ideas, and think outside established patterns. AI researchers invent new architectures; penetration testers devise novel attack chains. Both require the courage to explore paths others haven't taken.",
    tools: [],
    learningSources: {
      courses: ["Creative Problem Solving (IDEO U)", "Lateral Thinking (Edward de Bono)"],
      labs: ["Brainstorming sprints for technical challenges (SCAMPER method)"],
      projects: ["Design an unconventional solution to a known security or AI problem and present it"],
    },
    prereqs: ["curiosity", "analytical"],
    careers: ["AI Research Scientist", "Penetration Tester", "Applied AI Engineer"],
    salary: null,
    xp: 80,
  },
  {
    id: "problem_solving",
    label: "Problem\nSolving",
    icon: "💡",
    tier: "branch",
    branch: "ai",
    x: 450, y: 490,
    radius: 32,
    desc: "Structured approaches to diagnosing issues and finding effective solutions under constraints. From debugging a broken ML pipeline to investigating an active breach, having a clear problem-solving methodology prevents panic and drives resolution.",
    tools: [],
    learningSources: {
      courses: ["Design Thinking Bootleg (Stanford d.school)", "Problem Solving with Algorithms (book)"],
      labs: ["Weekly coding challenges", "Security CTF participation"],
      projects: ["Solve and publicly document 10 algorithmic or security challenges with your reasoning"],
    },
    prereqs: ["analytical", "curiosity"],
    careers: ["ML Engineer", "Applied AI Engineer", "Edge AI Engineer", "Resilient Autonomous Systems Engineer"],
    salary: null,
    xp: 80,
  },
  {
    id: "ethical_judgment",
    label: "Ethical\nJudgment",
    icon: "⚖️",
    tier: "branch",
    branch: "cyber",
    x: 950, y: 490,
    radius: 32,
    desc: "Knowing when and how to act responsibly — from responsible disclosure in security to fairness in AI systems. Ethical judgment prevents harm, builds trust with users and clients, and is increasingly a required competency in both fields.",
    tools: [],
    learningSources: {
      courses: ["AI Ethics (fast.ai)", "Ethics in Cybersecurity (SANS reading list)"],
      labs: ["Bias audit exercise on a public dataset", "Responsible disclosure scenario workshop"],
      projects: ["Write an ethical review of a real AI product or security practice"],
    },
    prereqs: ["communication", "attention"],
    careers: ["AI Security Engineer", "Security Architect", "Adversarial ML Engineer", "IoT Security Engineer"],
    salary: null,
    xp: 80,
  },
  {
    id: "persistence",
    label: "Persistence &\nResilience",
    icon: "🔥",
    tier: "branch",
    branch: "cyber",
    x: 1150, y: 490,
    radius: 32,
    desc: "Security investigations can span days; ML experiments fail hundreds of times before converging. The ability to stay focused, recover from setbacks, and push through ambiguity is what separates professionals from beginners in both disciplines.",
    tools: [],
    learningSources: {
      courses: ["Grit (book, Angela Duckworth)", "The Obstacle Is the Way (Ryan Holiday)"],
      labs: ["Multi-day CTF challenges", "Long-form research or investigation projects"],
      projects: ["Complete a 30-day learning streak on any technical platform and reflect on the experience"],
    },
    prereqs: ["attention"],
    careers: ["Incident Response Engineer", "Security Analyst", "Embedded ML Engineer"],
    salary: null,
    xp: 80,
  },

  // ══════════════════════════════════════════════════
  //  ADVANCED SOFT SKILLS
  // ══════════════════════════════════════════════════
  {
    id: "scientific_comm",
    label: "Scientific\nCommunication",
    icon: "📢",
    tier: "advanced",
    branch: "ai",
    x: 160, y: 330,
    radius: 34,
    desc: "Writing research papers, crafting technical presentations, and communicating experimental results with precision and intellectual honesty. Essential for AI researchers publishing findings, collaborating across institutions, or influencing product decisions with data.",
    tools: [],
    learningSources: {
      courses: ["Writing in the Sciences (Coursera/Stanford)", "How to Write a Paper (Nature guide)"],
      labs: ["Reproduce and summarise a landmark research paper", "Write a conference-style abstract"],
      projects: ["Publish a technical blog post or preprint on a research finding or experiment"],
    },
    prereqs: ["creative_thinking", "communication"],
    careers: ["AI Research Scientist"],
    salary: null,
    xp: 120,
  },
  {
    id: "systems_thinking",
    label: "Systems\nThinking",
    icon: "🌐",
    tier: "advanced",
    branch: "hybrid",
    x: 440, y: 330,
    radius: 34,
    desc: "Understanding how components interact within a system, where failure cascades, and how changes ripple through interconnected parts. Critical for designing secure AI architectures, predicting attacker behavior, and reasoning about complex autonomous systems.",
    tools: [],
    learningSources: {
      courses: ["Thinking in Systems (book, Donella Meadows)", "Systems Thinking for Social Change"],
      labs: ["Threat modelling a real application using STRIDE", "Dependency mapping exercise"],
      projects: ["Create a full system diagram with failure modes and attack surfaces for a real product"],
    },
    prereqs: ["problem_solving", "ethical_judgment"],
    careers: ["AI Security Engineer", "Resilient Autonomous Systems Engineer", "ML Engineer", "Edge AI Engineer"],
    salary: null,
    xp: 120,
  },
  {
    id: "strategic_thinking",
    label: "Strategic\nThinking",
    icon: "🎯",
    tier: "advanced",
    branch: "cyber",
    x: 960, y: 330,
    radius: 34,
    desc: "Seeing the big picture — aligning security posture with organizational goals, prioritizing risk, and making decisions with incomplete information. Security architects and threat intelligence analysts must think several moves ahead to stay ahead of adversaries.",
    tools: [],
    learningSources: {
      courses: ["Strategic Thinking (LinkedIn Learning)", "Good Strategy / Bad Strategy (book, Richard Rumelt)"],
      labs: ["Tabletop security exercise as a planner", "Risk prioritization workshop"],
      projects: ["Write a 2-page strategic risk assessment for a real or hypothetical organization"],
    },
    prereqs: ["ethical_judgment", "problem_solving"],
    careers: ["Security Architect", "Threat Intel Engineer", "Resilient Autonomous Systems Engineer"],
    salary: null,
    xp: 120,
  },
  {
    id: "leadership",
    label: "Leadership &\nCoordination",
    icon: "👑",
    tier: "advanced",
    branch: "cyber",
    x: 1180, y: 330,
    radius: 34,
    desc: "Coordinating teams under pressure, making decisions during active incidents, and influencing direction without direct authority. Incident response engineers and security architects must lead calmly and decisively when the stakes are highest.",
    tools: [],
    learningSources: {
      courses: ["Dare to Lead (Brené Brown)", "The Manager's Path (book, Camille Fournier)"],
      labs: ["Tabletop incident simulation as lead responder", "Structured peer feedback sessions"],
      projects: ["Lead a team project end-to-end and write a detailed retrospective on lessons learned"],
    },
    prereqs: ["ethical_judgment", "persistence"],
    careers: ["Security Architect", "Incident Response Engineer"],
    salary: null,
    xp: 120,
  },

  // ══════════════════════════════════════════════════
  //  CAREER ENDPOINTS — AI
  // ══════════════════════════════════════════════════
  {
    id: "data_sci",
    label: "Data\nScientist",
    icon: "📊",
    tier: "career",
    branch: "ai",
    x: 200, y: 100,
    radius: 44,
    desc: "Extracts insights from complex datasets to drive business decisions. Works at the intersection of statistics, domain expertise, and software engineering.",
    tools: ["Python", "R", "Tableau", "SQL", "Jupyter", "Spark"],
    softSkills: ["Communication", "Analytical Thinking", "Business Translation", "Curiosity"],
    learningSources: {
      courses: ["Applied Data Science with Python (Coursera)", "Kaggle Data Science micro-courses"],
      labs: ["Kaggle notebook competitions", "Seaborn & Matplotlib visualisation exercises"],
      projects: ["End-to-end EDA and prediction project", "Build an interactive data dashboard"],
    },
    prereqs: ["analytical", "communication"],
    careers: [],
    salary: "$105K – $165K / yr",
    xp: 200,
  },
  {
    id: "ml_eng",
    label: "ML\nEngineer",
    icon: "🤖",
    tier: "career",
    branch: "ai",
    x: 390, y: 80,
    radius: 44,
    desc: "Designs, trains, and deploys production-grade ML systems. A blend of software engineering discipline and data science expertise.",
    tools: ["PyTorch", "TensorFlow", "Kubernetes", "FastAPI", "MLflow"],
    softSkills: ["Analytical Thinking", "Problem Solving", "Collaboration", "Communication"],
    learningSources: {
      courses: ["MLOps Specialization (DeepLearning.AI)", "Full Stack Deep Learning"],
      labs: ["Build and serve a model with FastAPI", "Kubeflow pipeline lab"],
      projects: ["Deploy a production ML system with monitoring", "A/B test a model in a staging environment"],
    },
    prereqs: ["systems_thinking", "problem_solving"],
    careers: [],
    salary: "$130K – $200K / yr",
    xp: 200,
  },
  {
    id: "ai_researcher",
    label: "AI Research\nScientist",
    icon: "🧬",
    tier: "career",
    branch: "ai",
    x: 70, y: 80,
    radius: 44,
    desc: "Invents new AI algorithms and architectures. Publishes research, works on frontier models, and often requires a PhD or equivalent research experience.",
    tools: ["PyTorch", "JAX", "Hugging Face", "LaTeX", "CUDA"],
    softSkills: ["Curiosity & Continuous Learning", "Creativity / Innovation", "Analytical Thinking", "Scientific Communication"],
    learningSources: {
      courses: ["Deep Learning Specialization (DeepLearning.AI)", "CS231n / CS224n (Stanford)"],
      labs: ["Reproduce a landmark research paper (ResNet, BERT)", "Hugging Face research model lab"],
      projects: ["Publish an AI research blog post or preprint", "Novel architecture experiment on a benchmark"],
    },
    prereqs: ["scientific_comm", "creative_thinking"],
    careers: [],
    salary: "$160K – $350K+ / yr",
    xp: 200,
  },

  // ══════════════════════════════════════════════════
  //  CAREER ENDPOINTS — CYBERSECURITY
  // ══════════════════════════════════════════════════
  {
    id: "pen_tester",
    label: "Penetration\nTester",
    icon: "🎯",
    tier: "career",
    branch: "cyber",
    x: 920, y: 130,
    radius: 44,
    desc: "Ethically hacks systems to find and report vulnerabilities before malicious actors can exploit them. Operates under legal agreements and structured methodologies.",
    tools: ["Metasploit", "Burp Suite", "Kali Linux", "OWASP", "Cobalt Strike"],
    softSkills: ["Creativity", "Problem Solving", "Curiosity", "Ethical Judgment"],
    learningSources: {
      courses: ["OSCP (Offensive Security)", "TCM Security: Practical Bug Bounty"],
      labs: ["HackTheBox Pro Labs", "TryHackMe offensive paths"],
      projects: ["Submit a bug bounty finding", "Write a full penetration test report on a lab VM"],
    },
    prereqs: ["creative_thinking", "ethical_judgment"],
    careers: [],
    salary: "$95K – $155K / yr",
    xp: 200,
  },
  {
    id: "sec_arch",
    label: "Security\nArchitect",
    icon: "🏛",
    tier: "career",
    branch: "cyber",
    x: 1100, y: 100,
    radius: 44,
    desc: "Designs and oversees the security posture of entire organizations. Requires broad expertise across networking, cloud, identity, and risk management.",
    tools: ["NIST Framework", "AWS/GCP/Azure Security", "Zero Trust", "SIEM"],
    softSkills: ["Strategic Thinking", "Communication", "Risk Assessment", "Leadership"],
    learningSources: {
      courses: ["CISSP Exam Prep", "AWS/GCP Security Specialty certification"],
      labs: ["Design a zero-trust architecture on paper", "Cloud security misconfiguration lab"],
      projects: ["Enterprise security assessment report", "Threat model a real application using STRIDE"],
    },
    prereqs: ["strategic_thinking", "leadership"],
    careers: [],
    salary: "$140K – $220K / yr",
    xp: 200,
  },
  {
    id: "ir_analyst",
    label: "Incident Response\nEngineer",
    icon: "🚨",
    tier: "career",
    branch: "cyber",
    x: 1270, y: 130,
    radius: 44,
    desc: "Investigates active breaches, contains damage, eradicates threats, and leads recovery. Acts as the digital first responder when an organization is under attack.",
    tools: ["Splunk", "CrowdStrike", "Volatility", "The Hive", "Elastic"],
    softSkills: ["Crisis Decision Making", "Attention to Detail", "Communication", "Team Coordination"],
    learningSources: {
      courses: ["GCIH (GIAC Certified Incident Handler)", "SANS FOR508: Digital Forensics"],
      labs: ["Blue Team Labs Online: IR scenarios", "LetsDefend incident response labs"],
      projects: ["Incident response simulation exercise", "Build a detection-to-response playbook"],
    },
    prereqs: ["strategic_thinking", "persistence"],
    careers: [],
    salary: "$90K – $150K / yr",
    xp: 200,
  },

  // ══════════════════════════════════════════════════
  //  HYBRID CAREERS
  // ══════════════════════════════════════════════════
  {
    id: "ai_sec_eng",
    label: "AI Security\nEngineer",
    icon: "🔐",
    tier: "career",
    branch: "hybrid",
    x: 620, y: 120,
    radius: 44,
    desc: "Secures AI/ML systems against adversarial attacks — data poisoning, model inversion, prompt injection, and model theft. A rare, high-demand intersection role.",
    tools: ["CleverHans", "ART (IBM)", "MLflow", "OWASP ML", "TensorFlow Privacy"],
    softSkills: ["Adversarial Thinking", "Analytical Thinking", "Collaboration", "Ethical Judgment"],
    learningSources: {
      courses: ["AI Security (MITRE ATLAS free training)", "Adversarial Robustness Toolbox tutorials"],
      labs: ["Adversarial ML Exercise (IBM ART)", "OWASP ML Security Top 10 lab"],
      projects: ["Secure Model Deployment pipeline", "Demonstrate a data poisoning attack and its defence"],
    },
    prereqs: ["systems_thinking", "ethical_judgment"],
    careers: [],
    salary: "$150K – $230K / yr",
    xp: 250,
  },
  {
    id: "threat_intel",
    label: "Threat Intel\nEngineer",
    icon: "🔍",
    tier: "career",
    branch: "hybrid",
    x: 780, y: 120,
    radius: 44,
    desc: "Uses AI and ML to detect, classify, and predict emerging cyber threats at scale. Combines statistical anomaly detection with deep threat intelligence tradecraft.",
    tools: ["MITRE ATT&CK", "OpenCTI", "ML anomaly models", "STIX/TAXII"],
    softSkills: ["Pattern Recognition", "Analytical Thinking", "Communication", "Curiosity"],
    learningSources: {
      courses: ["MITRE ATT&CK Fundamentals (free)", "SANS FOR578: Cyber Threat Intelligence"],
      labs: ["OpenCTI platform setup lab", "STIX/TAXII data modelling exercise"],
      projects: ["Threat intelligence report on a real APT group", "Build an AI anomaly detector for network logs"],
    },
    prereqs: ["analytical", "strategic_thinking"],
    careers: [],
    salary: "$110K – $180K / yr",
    xp: 250,
  },

  // ══════════════════════════════════════════════════
  //  CAREER ENDPOINTS — AI SYSTEMS (panel-only)
  // ══════════════════════════════════════════════════
  {
    id: "applied_ai_eng",
    label: "Applied AI\nEngineer",
    icon: "⚡",
    tier: "career",
    branch: "ai",
    panelOnly: true,
    x: 0, y: 0, radius: 44,
    desc: "Translates AI research into real-world products — recommendation systems, search engines, NLP pipelines, and vision systems. Heavy emphasis on production reliability and scale.",
    tools: ["PyTorch", "TensorFlow", "FastAPI", "Docker", "Redis", "gRPC"],
    softSkills: ["Problem Solving", "Collaboration", "Strategic Thinking", "Adaptability"],
    learningSources: {
      courses: ["Full Stack Deep Learning", "Designing ML Systems (book by Chip Huyen)"],
      labs: ["Build an ML-powered REST API", "System design mock interviews for ML"],
      projects: ["Deploy a recommendation system to production", "Build a real-time ML feature pipeline"],
    },
    prereqs: ["systems_thinking", "problem_solving"],
    careers: [],
    salary: "$125K – $195K / yr",
    xp: 200,
  },

  // ══════════════════════════════════════════════════
  //  CAREER ENDPOINTS — CYBERSECURITY (panel-only)
  // ══════════════════════════════════════════════════
  {
    id: "sec_analyst",
    label: "Security\nAnalyst",
    icon: "🔎",
    tier: "career",
    branch: "cyber",
    panelOnly: true,
    x: 0, y: 0, radius: 44,
    desc: "Monitors networks and systems for threats, triages security alerts, and performs initial investigation of potential incidents. Often the entry point into a SOC career.",
    tools: ["Splunk", "QRadar", "Elastic SIEM", "Wireshark", "MITRE ATT&CK"],
    softSkills: ["Attention to Detail", "Analytical Thinking", "Communication", "Persistence"],
    learningSources: {
      courses: ["CompTIA CySA+", "Google Cybersecurity Certificate (Coursera)"],
      labs: ["Splunk Boss of the SOC (BOTS v1)", "LetsDefend SOC analyst labs"],
      projects: ["SOC alert triage simulation write-up", "Build a SIEM dashboard for a home lab"],
    },
    prereqs: ["analytical", "attention"],
    careers: [],
    salary: "$70K – $120K / yr",
    xp: 150,
  },

  // ══════════════════════════════════════════════════
  //  CAREER ENDPOINTS — EDGE / EMBEDDED AI (panel-only)
  // ══════════════════════════════════════════════════
  {
    id: "edge_ai_eng",
    label: "Edge AI\nEngineer",
    icon: "📡",
    tier: "career",
    branch: "edge",
    panelOnly: true,
    x: 0, y: 0, radius: 44,
    desc: "Deploys and optimizes AI models on resource-constrained hardware — smartphones, cameras, sensors, and microcontrollers. Specializes in model compression, quantization, and on-device inference.",
    tools: ["TensorFlow Lite", "ONNX", "OpenVINO", "NVIDIA Jetson", "CoreML", "TVM"],
    softSkills: ["Systems Thinking", "Problem Solving", "Collaboration", "Adaptability"],
    learningSources: {
      courses: ["Edge AI Systems (Coursera)", "TinyML Specialization (HarvardX/edX)"],
      labs: ["Deploy a model on Raspberry Pi / Jetson Nano", "TensorFlow Lite quantisation lab"],
      projects: ["Real-time object detection on a mobile device", "Benchmark three compression strategies on a CNN"],
    },
    prereqs: ["systems_thinking", "problem_solving"],
    careers: [],
    salary: "$110K – $175K / yr",
    xp: 200,
  },
  {
    id: "embedded_ml_eng",
    label: "Embedded ML\nEngineer",
    icon: "🔧",
    tier: "career",
    branch: "edge",
    panelOnly: true,
    x: 0, y: 0, radius: 44,
    desc: "Writes ML inference code for bare-metal microcontrollers and FPGAs. Bridges hardware engineering and machine learning — optimizing every byte and clock cycle.",
    tools: ["TensorFlow Micro", "C/C++", "CMSIS-NN", "Arduino", "STM32", "FPGA"],
    softSkills: ["Attention to Detail", "Analytical Thinking", "Problem Solving", "Persistence"],
    learningSources: {
      courses: ["Embedded Systems (Coursera/EE)", "TensorFlow Micro (Arduino/ST)"],
      labs: ["Keyword spotting demo on Arduino Nano 33 BLE", "CMSIS-NN inference lab"],
      projects: ["Keyword spotting model on a microcontroller", "FPGA-accelerated ML inference demo"],
    },
    prereqs: ["problem_solving", "attention"],
    careers: [],
    salary: "$105K – $165K / yr",
    xp: 200,
  },
  {
    id: "robotics_eng",
    label: "Robotics & Autonomous\nSystems Engineer",
    icon: "🦾",
    tier: "career",
    branch: "edge",
    panelOnly: true,
    x: 0, y: 0, radius: 44,
    desc: "Builds intelligent autonomous agents — drones, self-driving vehicles, robotic arms, and UAVs. Combines computer vision, motion planning, and real-time control with ML.",
    tools: ["ROS/ROS2", "OpenCV", "PyTorch", "Gazebo", "SLAM algorithms", "C++"],
    softSkills: ["Systems Thinking", "Problem Solving", "Collaboration", "Adaptability"],
    learningSources: {
      courses: ["Robotics Specialization (Coursera/Penn)", "Self-Driving Car Engineer (Udacity)"],
      labs: ["ROS2 simulation lab (Gazebo)", "OpenCV vision pipeline lab"],
      projects: ["Autonomous navigation demo in simulation", "Computer vision object-tracking robot"],
    },
    prereqs: ["systems_thinking", "problem_solving"],
    careers: [],
    salary: "$115K – $185K / yr",
    xp: 200,
  },
  {
    id: "iot_sec_eng",
    label: "IoT Security\nEngineer",
    icon: "🌐",
    tier: "career",
    branch: "edge",
    panelOnly: true,
    x: 0, y: 0, radius: 44,
    desc: "Secures the vast landscape of connected devices — identifying firmware vulnerabilities, hardening device boot chains, and designing secure OTA update mechanisms.",
    tools: ["Firmware analysis", "Binwalk", "OpenWRT", "MQTT security", "Shodan", "Zigbee"],
    softSkills: ["Attention to Detail", "Analytical Thinking", "Problem Solving", "Ethical Judgment"],
    learningSources: {
      courses: ["IoT Security Fundamentals (SANS)", "Embedded Security (Coursera)"],
      labs: ["Firmware analysis with Binwalk", "MQTT security testing lab"],
      projects: ["IoT device security audit report", "Harden an off-the-shelf IoT device"],
    },
    prereqs: ["ethical_judgment", "attention"],
    careers: [],
    salary: "$100K – $160K / yr",
    xp: 200,
  },

  // ══════════════════════════════════════════════════
  //  CAREER ENDPOINTS — AI + CYBER HYBRID (panel-only)
  // ══════════════════════════════════════════════════
  {
    id: "adv_ml_eng",
    label: "Adversarial ML\nEngineer",
    icon: "⚔",
    tier: "career",
    branch: "hybrid",
    panelOnly: true,
    x: 0, y: 0, radius: 44,
    desc: "Researches and defends against adversarial attacks on AI — crafting and defeating adversarial examples, data poisoning campaigns, and model extraction attacks. One of the most cutting-edge roles in the field.",
    tools: ["CleverHans", "Foolbox", "IBM ART", "PyTorch", "MITRE ATLAS"],
    softSkills: ["Adversarial Thinking", "Curiosity", "Analytical Thinking", "Ethical Judgment"],
    learningSources: {
      courses: ["Adversarial ML (MITRE ATLAS training)", "Robust ML course (CMU)"],
      labs: ["Adversarial ML Exercise (Foolbox / CleverHans)", "MITRE ATLAS attack simulation"],
      projects: ["Attack and defend an ML model challenge", "Reproduce an adversarial example paper"],
    },
    prereqs: ["creative_thinking", "ethical_judgment"],
    careers: [],
    salary: "$140K – $220K / yr",
    xp: 250,
  },
  {
    id: "resilient_auto_eng",
    label: "Resilient Autonomous\nSystems Engineer",
    icon: "🛡",
    tier: "career",
    branch: "hybrid",
    panelOnly: true,
    x: 0, y: 0, radius: 44,
    desc: "Designs autonomous systems — drones, vehicles, robots — that remain safe and functional under cyberattack, sensor spoofing, and adversarial conditions. Combines robotics, AI safety, and cybersecurity.",
    tools: ["ROS2", "Formal verification", "MITRE ATT&CK for ICS", "Gazebo", "OpenCV"],
    softSkills: ["Systems Thinking", "Crisis Decision Making", "Strategic Thinking", "Problem Solving"],
    learningSources: {
      courses: ["Resilient Systems Design (MIT OpenCourseWare)", "Autonomous Vehicle Security (SANS)"],
      labs: ["ROS2 adversarial sensor spoofing simulation", "Fault injection lab on a robotic arm"],
      projects: ["Fault-tolerant autonomous navigation demo", "Red team a simulated autonomous vehicle pipeline"],
    },
    prereqs: ["systems_thinking", "strategic_thinking"],
    careers: [],
    salary: "$130K – $210K / yr",
    xp: 250,
  },
];

// Build a lookup map for convenience
const SKILL_MAP = Object.fromEntries(SKILLS.map(s => [s.id, s]));

// Edge definitions: [from_id, to_id]
// Auto-generated from prereqs but we define them explicitly for control
const EDGES = SKILLS.flatMap(skill =>
  skill.prereqs.map(prereqId => ({ from: prereqId, to: skill.id }))
);
